spring.application.name=backend


#databse settings
spring.datasource.url = jdbc:mysql://localhost:3306/carebridge
spring.datasource.username = root
spring.datasource.password = 2003

#jpa settings
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

#port settings
server.port = 8080

#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carebridge086@gmail.com
spring.mail.password=krlq dwqw witx vqrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#jwt settings
jwt.secret = carebridgeprojecthelporpsdonors@1252026good22d31a6648
jwt.expiration = 86400000


#CDN Settings
cloudinary.cloud-name=dli5j4div
cloudinary.api-key=891676235696776
cloudinary.api-secret=C9tN120w8vT60mTY-o3X-dxRZNE